<?php

namespace GraphBundle\Repository;

/**
 * Spo2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Spo2Repository extends \Doctrine\ORM\EntityRepository
{
}
