parameters:
    database_host_dev: localhost
    database_port_dev: null
    database_name_dev: spo2_dev
    database_user_dev: root
    database_password_dev: root
    #database_path: "%kernel.root_dir%/data/spo2.sqlite3"

    mailer_transport_dev: smtp
    mailer_host_dev: 127.0.0.1
    mailer_user_dev: null
    mailer_password_dev: null
    secret_dev: 386fc86db1ad9260f1ab051055b1daf8b04b032e
