parameters:
    database_host_test: 127.0.0.1
    database_port_test: null
    database_name_test: spo2_dev
    database_user_test: root
    database_password_test: iamroot
    mailer_transport_test: smtp
    mailer_host_test: 127.0.0.1
    mailer_user_test: null
    mailer_password_test: null
    secret_test: 386fc86db1ad9260f1ab051055b1daf8b04b032e
